#!/usr/bin/php
<?php

  require_once 'invoice_generator_class.php';
  
  if( $argc < 3 )
    print 'usage: ' . $argv[ 0 ] . " [path_to_invoice_file .inv] [path_for_pdf]\n";
  
  if( !file_exists( $argv[ 1 ]))
    print 'usage: ' . $argv[ 0 ] . " [path_to_invoice_file .inv] [path_for_pdf]\n";
  
  if( !is_dir( $argv[ 2 ]) && !mkdir( $argv[ 2 ], 0755, true ))
    print 'usage: ' . $argv[ 0 ] . " [path_to_invoice_file .inv] [path_for_pdf]\n";
  
  $explod_inv = explode( '/', $argv[ 1 ]);
  $explode_name = explode( '.', $explod_inv[ sizeof( $explod_inv ) - 1 ] );
  unset( $explode_name[ sizeof( $explode_name ) - 1 ]);
  $pdf_name = implode( '.', $explode_name );
  
  try {
  
    require_once 'models/StdInvoice.php';
    $invoice_gen = new InvoiceGenerator( Invoice::load( $argv[ 1 ]));
    $invoice_gen -> generate(
      $argv[ 2 ] . $pdf_name . '.pdf'
    );
  
  } catch( Exception $e ) {
  
    print $e -> getMessage() ."\n";
  
  }

